routes/web.php
<?php

Route::get('/', 'PagesController@index')->name('index');
Route::get('/login', 'PagesController@index')->name('login');
Route::get('/all/project','PagesController@ProjectAll')->name('allproject');
Route::get('/all/gallery','PagesController@Gallery')->name('allgallery');
Route::get('/contact','PagesController@Users')->name('profile');
Route::post('/send/message','PagesController@sendMessage')->name('sendmessage');
Route::get('/view/project/{id}','PagesController@viewProject')->name('viewproject');
Route::post('/send/comment', 'PagesController@sendComment')->name('send-comment');

Route::get('logout','PagesController@logOut')->name('logout');


Route::post('/login','PagesController@postLogin')->name('login');

//adding middleware
Route::group(['middleware' => ['auth']], function () {
    Route::resource('/user','API\UserController');
    Route::resource('/project', 'API\ProjectController');
    Route::resource('/carousel','API\CarouselController');
    Route::resource('/comment','API\CommentController');
    Route::resource('/message','API\MessageController');
    Route::resource('/gallery','API\GalleryController');
    Route::get('/title/get','API\ProjectController@projectTitle');
});




//admin route

Route::get('/home', 'HomeController@index')->name('home');
Route::get('{path}',"HomeController@index")->where('path', '([A-z\d-\/_.]+)?');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Authenticatable
{
    use Notifiable;
    use SoftDeletes;
    protected $dates = ['deleted_at'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = [];

    public function getPhotoAttribute($value){
        return asset('img/users/'.$value);
    }

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function projects(){
        $this->hasMany(Project::class);
    }
}

app/Http/Controllers/PagesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Carousel;
use App\Message;
use App\User;
use App\Project;
use App\Gallery;
use App\Comment;
use DB;
use Auth;
use Validator;

class PagesController extends Controller
{
    public function index(){
        $carousels = Carousel::latest()->paginate(10);
        $projects = Project::with(['user','comments'])->withCount('comments')->latest()->paginate(6);
        $galleries = Gallery::with('project')->latest()->paginate(12);
        return view('pages.index', compact('carousels','projects','galleries'));
     }

    public function Users(){
        $users = User::latest()->paginate(6);
        return view('pages.contact', compact('users'));
    }

    public function Gallery(){
        $galleries = Gallery::with('project')->latest()->paginate(18);
        return view('pages.gallery', compact('galleries'));
    }

    public function ProjectAll(){
        $projects = Project::with(['user','comments'])->withCount('comments')->latest()->paginate(12);
        return view('pages.projects', compact('projects'));
    }

    public function sendMessage(Request $request){
        $validator = Validator::make($request->all(), [
            'name'=>'required|string',
            'email'=>'required|email',
            'contact'=>'required',
            'body' => 'required:string',
        ]);

        if ($validator->fails()){
            return redirect()->back()->with('error','Check and fill all required field');
        }

        $message = new Message();
        $message->name = $request['name'];
        $message->email = $request['email'];
        $message->contact = $request['contact'];
        $message->body = $request['body'];

        if ($message->save()){
            return redirect()->back()->with('message','Your Message Send Successfully');
        } else {
            return redirect()->back()->with('error','Failed to send Message');
        }
    }

    public function viewProject($id){
      $project = Project::with('user')->where('id',$id)->where('deleted_at',null)->first();
      $galleries = Gallery::where('project_id',$id)->where('deleted_at',null)->get();
      $projects = Project::with('user')->latest()->paginate(6);
      $comments = Comment::where('project_id',$id)->where('deleted_at',null)->orderBy('created_at','desc')->get();
      return view('pages.viewproject', compact('project','galleries','projects','comments'));
    }

    public function sendComment(Request $request){
        $validator = Validator::make($request->all(), [
            'project_id'=>'required',
            'comment'=>'required|string',
        ]);

        if ($validator->fails()){
            return redirect()->back()->with('error','Check and fill all required field');
        }

        $comment = new Comment();
        $comment->project_id = $request['project_id'];
        $comment->comment = $request['comment'];
        $comment->save();

        return redirect()->back();
    }

    public function logOut(){
        Auth::logout();
        return redirect()->route('index');
    }

    public function postLogin(Request $request){
        if(Auth::attempt(['email'=>$request->email, 'password'=>$request->password], $request->remember)){
            return redirect()->route('home');
        }else{
            return redirect()->route('index')->with('error','Invalid Login Credentials');
        }
    }
}

resources/views/pages/carousel.blade.php
<section class="hero-home">
  <div class="swiper-container hero-slider">
    <div class="swiper-wrapper dark-overlay">

       @foreach ($carousels as $carousel)
         <div style="background-image:url({{ $carousel->photo }})" class="swiper-slide">
           <div class="container py-6 py-md-7 text-white z-index-20">
             <div class="row">
               <div class="col-xl-12">
                 <div class="text-center text-lg-left">
                   <p class="subtitle letter-spacing-2 mb-2 text-primary text-shadow">{{$carousel->description}}</p>
                   <h1 class="display-3 font-weight-bold text-shadow text-md">{{$carousel->title}}</h1>
                 </div>
               </div>
             </div>
           </div>
         </div>
       @endforeach

    </div>
  </div>

</section>

resources/views/pages/contact.blade.php
@extends('layouts.pages')

@section('section')

    <section class="py-3 bg-gray-100">
        <div class="container">

            <div class="row mb-5">
                <div class="col-md-8">
                    <p class="subtitle text-secondary">Contact and profile of leaders</p>
                    <h2>Profile Information</h2>
                </div>
            </div>
            <!-- Additional required wrapper-->
            <div class="row">

                @foreach($users as $user)
                    <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 swiper-container mb-5">

                        <div class="card h-100 border-0 shadow">
                            <div class="card-img-top overflow-hidden gradient-overlay">
                                <img src="{{$user->photo}}" alt="Modern, Well-Appointed Room" class="img img-responsive" width="100%"/>
                                <div class="card-img-overlay-bottom z-index-20">
                                    <div class="media text-white text-sm align-items-center"><img src="{{$user->photo}}" alt="Pamela" class="avatar avatar-border-white mr-2"/>
                                        <div class="media-body"><strong>{{$user->name}}</strong></div>
                                    </div>
                                </div>
                            </div>

                            <div class="card-body d-flex align-items-center">
                                <div class="w-100">
                                    <h6 class="card-title">
                                        <i class="fa fa-envelope"></i>
                                        <a class="text-decoration-none text-dark">{{ $user->email }}</a>
                                    </h6>
                                    <div class="d-flex card-subtitle mb-3">
                                        <p class="flex-grow-1 mb-0 text-muted text-sm">Position: {{ $user->position}}</p>

                                    </div>
                                    <p class="card-text text-muted"><span class="h4 text-primary"> <i class="fa fa-phone"></i> {{ $user->contact}}</span></p>
                                </div>
                            </div>

                        </div>
                    </div>
                @endforeach

            </div>

            <div class="row">
                <div class="col-lg-1 col-md-1 col-sm-1 col-xs-0"></div>
                <div class="col-lg-10 col-md-10 col-sm-10 col-xs-12">
                    <div class="pagination justify-content-center pagination-lg">
                        {{ $users->links() }}
                    </div>
                </div>
                <div class="col-lg-1 col-md-1 col-sm-1 col-xs-0"></div>
            </div>

        </div>
    </section>

@endsection

resources/views/pages/footer.blade.php
<!-- Footer-->
<footer class="position-relative z-index-10 d-print-none">
  <!-- Main block - menus, subscribe form-->
  <div class="py-4 bg-gray-200 text-muted">
    <div class="container">
      <div class="row">

        <div class="col-lg-6 mb-6 mb-lg-0">
          <div class="font-weight-bold text-uppercase text-dark mb-3">Social Media Links</div>
          <p>Contact us on the below social media links</p>
          <ul class="list-inline">
            <li class="list-inline-item"><a href="#" target="_blank" title="twitter" class="text-muted text-hover-primary"><i class="fab fa-twitter"></i></a></li>
            <li class="list-inline-item"><a href="#" target="_blank" title="facebook" class="text-muted text-hover-primary"><i class="fab fa-facebook"></i></a></li>
            <li class="list-inline-item"><a href="#" target="_blank" title="instagram" class="text-muted text-hover-primary"><i class="fab fa-instagram"></i></a></li>
            <li class="list-inline-item"><a href="#" target="_blank" title="pinterest" class="text-muted text-hover-primary"><i class="fab fa-pinterest"></i></a></li>
            <li class="list-inline-item"><a href="#" target="_blank" title="vimeo" class="text-muted text-hover-primary"><i class="fab fa-vimeo"></i></a></li>
          </ul>
        </div>

        <div class="col-lg-6">

          @include('partials.alerts')

          <h6 class="text-uppercase text-dark mb-3">Send Us Message</h6>

          <form class="form" action="{{route('sendmessage')}}" method="post">
            {{ csrf_field() }}
            <div class="input-group mb-3">
              <input type="text" name="name" placeholder="Enter Your Fullname" class="form-control bg-transparent border-dark border-right-0" required>
              <div class="input-group-append">
                <span class="btn btn-outline-dark border-left-0">
                  <i class="fa fa-user text-lg"></i>
                </span>
              </div>
            </div>
            <div class="input-group mb-3">
              <input type="email" name="email" placeholder="Enter Your Email Address" class="form-control bg-transparent border-dark border-right-0" required>
              <div class="input-group-append">
                <span class="btn btn-outline-dark border-left-0">
                  <i class="fa fa-envelope text-lg"></i>
                </span>
              </div>
            </div>
            <div class="input-group mb-3">
              <input type="text" name="contact" placeholder="Enter Your Contact Number" class="form-control bg-transparent border-dark border-right-0" required>
              <div class="input-group-append">
                <span class="btn btn-outline-dark border-left-0">
                  <i class="fa fa-phone text-lg"></i>
                </span>
              </div>
            </div>

            <div class="input-group mb-3">
              <textarea class="form-control bg-transparent border-dark" name="body" rows="6" cols="10" placeholder="Write your message here!" style="resize:none" required></textarea>
            </div>

            <div class="input-group">
              <button type="submit" name="button" class="btn btn-dark"> <i class="fa fa-paper-plane"></i> Send</button>
            </div>

          </form>

        </div>
      </div>
    </div>
  </div>
  <!-- Copyright section of the footer-->
  <div class="py-3 font-weight-light bg-gray-800 text-gray-300">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-md-6 text-center">
          <p class="text-sm mb-md-0">&copy; 2019 WASSA.  All rights reserved.</p>
        </div>
      </div>
    </div>
  </div>
</footer>
<!-- /Footer end-->

resources/views/pages/gallery.blade.php
@extends('layouts.pages')

@section('section')

    <section class="py-3 bg-white">
        <div class="container">
            <div class="row mb-5">
                <div class="col-md-8">
                    <p class="subtitle text-secondary">Stay and eat like a local</p>
                    <h2>Our Gallery</h2>
                </div>
            </div>
            <div class="row">

                @foreach($galleries as $gallery)

                    <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 swiper-container">
                        <div class="swiper-wrapper pb-5">

                            <div class="swiper-slide h-auto px-2">
                                <div class="card card-poster gradient-overlay mb-4 mb-lg-0">
                                    <a href="category.html" class="tile-link"></a>
                                    <img src="{{$gallery->image}}" alt="Card image" class="bg-image">
                                    <div class="card-body overlay-content">
                                        <h6 class="card-title text-shadow text-uppercase text-xs">{{ $gallery->project->title }}</h6>
                                        <p class="card-text text-sm">
                                            <i class="fa fa-stamp text-success"></i> <b>{{ $gallery->project->status }}</b>
                                        </p>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>

                @endforeach

            </div>
            <div class="row">
                <div class="col-lg-1 col-md-1 col-sm-1 col-xs-0"></div>
                <div class="col-lg-10 col-md-10 col-sm-10 col-xs-12">
                    <div class="pagination justify-content-center pagination-lg">
                        {{ $galleries->links() }}
                    </div>
                </div>
                <div class="col-lg-1 col-md-1 col-sm-1 col-xs-0"></div>
            </div>
        </div>
    </section>

@endsection

resources/views/pages/header.blade.php
<header class="header">
  <style>
    .navbar-nav li a::inactive-selection{
      background-color: red !important;
    }
  </style>
  <!-- Navbar-->
  <nav class="navbar navbar-expand-lg fixed-top shadow navbar-light bg-white">
    <div class="container-fluid">
      <div class="d-flex align-items-center">
       <router-link to="/" class="navbar-brand py-1">
          <img src="{{asset('../img/cups.png')}}" class="img-fluid" alt="logo"
        height="40px" width="40px">
        WASSA
      </router-link>
      </div>
      <button type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler navbar-toggler-right"><i class="fa fa-bars"></i></button>
      <!-- Navbar Collapse -->
      <div id="navbarCollapse" class="collapse navbar-collapse">
        <form action="#" id="searchcollapsed" class="form-inline mt-4 mb-2 d-sm-none">
          <div class="input-label-absolute input-label-absolute-left input-reset w-100">
            <label for="searchcollapsed_search" class="label-absolute"><i class="fa fa-search"></i><span class="sr-only">What are you looking for?</span></label>
            <input id="searchcollapsed_search" placeholder="Search" aria-label="Search" class="form-control form-control-sm border-0 shadow-0 bg-gray-200">
            <button type="reset" class="btn btn-reset btn-sm"><i class="fa-times fas">           </i></button>
          </div>
        </form>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a href="{{route('index')}}" class="nav-link"><i class="fa fa-home text-primary"></i> Home</a>
          </li>

          <li class="nav-item">
            <a href="{{route('allproject')}}" class="nav-link"><i class="fa fa-tasks text-secondary"></i> Projects</a>
          </li>

          <li class="nav-item">
            <a href="{{route('allgallery')}}" class="nav-link"><i class="fa fa-image text-info"></i> Gallery</a>
          </li>

          <li class="nav-item">
            <a href="{{route('profile')}}" class="nav-link"><i class="fa fa-user text-warning"></i> Contact</a>
          </li>

          <li><a href="" class="nav-link" data-toggle="modal" data-target="#myModal">
              <i class="fa fa-sign-in-alt"></i> Login</a>
          </li>

        </ul>
      </div>
    </div>
  </nav>

  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title text-center">Login</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form action="{{route('login')}}" method="post">
          {{ csrf_field() }}

          <div class="modal-body">
            <div class="form-group">
              <label><i class="fa fa-envelope"></i> Email</label>
              <input type="email" name="email" placeholder="Enter your email address" class="form-control">
            </div>

            <div class="form-group">
              <label><i class="fa fa-lock"></i> Password</label>
              <input type="password" name="password" placeholder="Enter your password" class="form-control">
            </div>

            <div class="form-group">
              <input type="checkbox" name="chk" id="chk"> Show Password
            </div>

            <div class="form-group">
              <button type="submit" name="button" class="btn btn-success"><i class="fa fa-sign-in-alt"></i> Login</button>
            </div>

          </div>
        </form>
      </div>
    </div>
  </div>

  <!-- /Navbar -->
</header>
<script>
  $(document).ready(function(){

  });
</script>

resources/views/pages/index.blade.php
@extends('layouts.pages')

@section('section')

    @include('pages.carousel')
    <section class="py-3 bg-gray-100">
        <div class="container">
            <div class="row mb-5">
                <div class="col-md-8">
                    <p class="subtitle text-secondary">Project in the Municipal</p>
                    <h2>On Going Projects</h2>
                </div>
            </div>
            <div class="row mb-5">
                <!-- blog item-->

                @foreach($projects as $project)
                    <div class="col-lg-4 col-sm-6 mb-4">
                        <div class="card shadow border-0 h-100">
                            <a href="{{route('viewproject',[$project->id])}}">
                                <img src="{{$project->photo}}" alt="..." class="img-fluid card-img-top"/>
                            </a>
                            <div class="card-body">
                                <a href="{{route('viewproject',[$project->id])}}" class="text-uppercase text-muted text-sm">Posted By : {{$project->user->name}}</a>
                                <p class="text-gray-500 text-sm my-3 text-left">
                                    <span class="text-left"><i class="far fa-clock"></i>{{ date('M j, Y', strtotime($project->created_at))}}</span>
                                    <span class="float-right text-success" style="margin-left: 100px"><i class="fa fa-stamp"></i> {{$project->status }}</span>
                                </p>
                                <h6>
                                    <a href="{{route('viewproject',[$project->id])}}" class="text-dark">{{ $project->title}}</a>
                                </h6>
                                <p class="my-2 text-muted text-sm">
                                    {{ str_limit($project->body, $limit = 150, $end = '...') }}
                                </p>
                                <a href="{{route('viewproject',[$project->id])}}" class="btn btn-primary btn-xs">read</a>
                                <span class="float-right">
                                    <i class="fa fa-comment"></i> {{$project->comments_count}} Comments
                                </span>
                            </div>
                        </div>
                    </div>
                @endforeach

            </div>



            <div class="row mb-5">
                <div class="col-md-8">
                    <p class="subtitle text-secondary">Project in the Municipal</p>
                    <h2>Galleries of Projects</h2>
                </div>
            </div>
            <div class="row">
                <div class="swiper-container guides-slider">
                    <!-- Additional required wrapper-->
                    <div class="swiper-wrapper pb-5">
                        <!-- Slides-->

                        @foreach($galleries as $gallery)
                            <div class="swiper-slide h-auto w-25 px-2">
                                <div class="card card-poster gradient-overlay mb-4 mb-lg-0">
                                    <img src="{{$gallery->image}}" alt="Card image" class="bg-image">
                                    <div class="card-body overlay-content">
                                        <h6 class="card-title text-shadow text-uppercase text-xs">{{ $gallery->project->title }}</h6>
                                        <p class="card-text text-sm">
                                            <i class="fa fa-stamp text-success"></i> <b>{{ $gallery->project->status }}</b>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        @endforeach

                    </div>

                </div>
            </div>

        </div>
    </section>

@endsection

resources/views/pages/projects.blade.php
@extends('layouts.pages')

@section('section')

    <section class="py-3 bg-gray-100">
        <div class="container">
            <div class="row mb-5">
                <div class="col-md-12">
                    <p class="subtitle text-secondary text-center">Project in the Municipal</p>
                    <h2 class="text-center">ALL PROJECTS AND THEIR STATUS</h2>
                </div>
            </div>

            <div class="row mb-5">
                <!-- blog item-->

                @foreach($projects as $project)

                    <div class="col-lg-4 col-sm-6 mb-4">
                        <div class="card shadow border-0 h-100">
                            <a href="post.html">
                                <img src="{{$project->photo}}" alt="..." class="img-fluid card-img-top"/>
                            </a>
                            <div class="card-body">
                                <a href="#" class="text-uppercase text-muted text-sm">Posted By : {{ $project->user->name }}</a>
                                <p class="text-gray-500 text-sm my-3 text-left">
                                    <span class="text-left">
                                        <i class="far fa-clock"></i>{{ date('M j, Y', strtotime($project->created_at))}}
                                    </span>
                                    <span class="float-right text-success" style="margin-left: 100px">
                                        <i class="fa fa-stamp"></i> {{ $project->status }}
                                    </span>

                                </p>
                                <p>
                                <h6>
                                    <a href="post.html" class="text-dark">{{$project->title}}</a>
                                </h6>
                                </p>
                                <p class="my-2 text-muted text-sm">
                                    {{ str_limit($project->body, $limit = 150, $end = '...') }}
                                </p>
                                <p>
                                    <a href="{{route('viewproject',[$project->id])}}" class="btn btn-primary">read</a>
                                    <span class="float-right">
                                       <i class="fa fa-comment"></i> {{$project->comments_count}} Comments
                                    </span>
                                </p>
                            </div>
                        </div>
                    </div>

                @endforeach


            </div>

            <div class="row">
                <div class="col-lg-1 col-md-1 col-sm-1 col-xs-0"></div>
                <div class="col-lg-10 col-md-10 col-sm-10 col-xs-12">
                    <div class="pagination justify-content-center pagination-lg">
                        {{ $projects->links() }}
                    </div>
                </div>
                <div class="col-lg-1 col-md-1 col-sm-1 col-xs-0"></div>
            </div>

        </div>
    </section>

@endsection